import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  disabled: {
    backgroundColor: '#d8d8d8',
    width: '76%',
    height: '17%',
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: '5%',
    justifyContent: 'center',
  },
  buttonTextDisabled: {
    color: '#878787',
    fontSize: 28,
    fontFamily: 'YanoneKaffeesatz-Bold',
  },
  logout: {
    backgroundColor: '#EA4335',
    width: '100%',
    height: '15%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: '5%',
    justifyContent: 'center',
  },
  buttonTextLogout: {
    color: '#F1F6FB',
    fontSize: 28,
    fontFamily: 'YanoneKaffeesatz-Bold',
  },
  menuBlue: {
    backgroundColor: '#475993',
    width: '100%',
    height: '15%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: '5%',
    justifyContent: 'center',
  },
  buttonTextMenuBlue: {
    color: '#F1F6FB',
    fontSize: 28,
    fontFamily: 'YanoneKaffeesatz-Bold',
  },
  menuWhite: {
    backgroundColor: '#F1F6FB',
    width: '100%',
    height: '15%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: '5%',
    justifyContent: 'center',
  },
  buttonTextMenuWhite: {
    color: '#333B65',
    fontSize: 28,
    fontFamily: 'YanoneKaffeesatz-Bold',
  },
  remove: {
    backgroundColor: '#EA4335',
    width: '76%',
    height: '15%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: '5%',
    justifyContent: 'center',
  },
  buttonTextRemove: {
    color: '#F1F6FB',
    fontSize: 28,
    fontFamily: 'YanoneKaffeesatz-Bold',
  },
  options: {
    backgroundColor: '#F1F6FB',
    width: '80%',
    height: '15%',
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: '5%',
    justifyContent: 'center',
  },
  buttonTextOptions: {
    color: '#020A32',
    fontSize: 26,
    fontFamily: 'YanoneKaffeesatz-Regular',
  },
  button: {
    backgroundColor: '#FFC90B',
    width: '76%',
    paddingBottom: 10,
    paddingTop: 10,
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: '5%',
    justifyContent: 'center',
  },
  buttonText: {
    color: '#5970E7',
    fontSize: 28,
    fontFamily: 'YanoneKaffeesatz-Bold',
  },
});
